### ISSUE TITLE
Upload of large file not working?

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass-docker#107]
Trying to replicate with https://s3.amazonaws.com/pkerp/public/Rao2014-GM12878-MboI-allreps-filtered.1kb.multires.cool (21GB)

**Comment by mccalluc** [comment]
@ngehlenborg : This is estimated to take 25minutes: Is that in the range that failed for you?

**Comment by ngehlenborg** [comment]
Yes, but the timeout is happening earlier, at least when I get the "Port in use" error message that I described earlier.

**Comment by mccalluc** [comment]
Ok, it doesn't seem to be related to large files per se, and in any case we want to just support local files, instead of downloading every time.
