### ISSUE TITLE
Should just download tarball for docs

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass-docker#11]
Installing node and npm brings in too many dependencies, particularly when we're just serving static docs. Instead, make a github release of the pre-built docs.

@flekschas : Does this sound reasonable? It might have been what you had in mind last week.

**Comment by flekschas** [comment]
Sounds good. I think we can use Travis to automatically add a built for all releases. (Similar to how it's done here: https://github.com/flekschas/owl2neo4j)

**Comment by flekschas** [comment]
Done. Every release as a zip of the compiled website attached to it. You can just unzip it. https://github.com/hms-dbmi/higlass-website/releases/tag/v0.1.0
