### ISSUE TITLE
Make PR for redis-conf updates

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass-docker#111]
When I look at https://github.com/hms-dbmi/higlass-docker/compare/with-redis-conf?expand=1 all I see is a version bump. If it's less trouble, feel free to paste the config changes you want here?

**Comment by pkerpedjiev** [comment]
Sorry, I forgot to actually commit my changes before pushing them. Should be there now.

**Comment by mccalluc** [comment]
I tool out the parts that seemed to matter and put them in #114
