### ISSUE TITLE
search box does not work

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/higlass-docker#134]
Release: v0.0.22

Adding the search box generates the following error in the console:

```javascript
GET http://localhost:8888/app/undefined 404 (Not Found)
```

The search box does not get updated and searching or even navigating to a provided set of  coordinates does not work. In the latter case, the following error is shown on the console:

```javascript
Uncaught TypeError: Cannot read property 'parsePosition' of null
```

**Comment by sidiropoulos** [comment]
I'm not sure if the question is relevant here but I can't find a more suitable place to post it.

I deployed a docker version of higlass with docker and I can't seem to find how to enable the search/navigation bar that is located on the top of the [higlass.io](http://higlass.io) instance.

**Comment by pkerpedjiev** [comment]
Oh, sorry that's not better documented. You should be able to add it using the "Toggle position search box" menu option of the view menu:

![image](https://user-images.githubusercontent.com/2143629/30029420-35962272-9157-11e7-859e-cc8a831c1243.png)

I'll add a documentation page before closing this issue. In the future, it might be better to post such questions on the [higlass github page](https://github.com/hms-dbmi/higlass/issues).

**Comment by sidiropoulos** [comment]
I feel a bit embarrassed that it was that simple.
Thank you very much for the quick response and for an amazing browser!

**Comment by pkerpedjiev** [comment]
It turns out it's already in the documentation. See the [view operations](https://github.com/hms-dbmi/higlass/wiki/View-Operations) section in the [HiGlass wiki](https://github.com/hms-dbmi/higlass/wiki/).

Please do not hesitate to ask about any other issues you encounter, no matter how seemingly simple they are :)
