### ISSUE TITLE
Blank data page

### ISSUE THREAD

**Issue by dborgesr** [hms-dbmi/higlass-docker#138]
Hello, 
I just tried pulling the Docker image and running it on a server, unfortunately when i go to use it from that server all I see is a blank page with no data ex:
<img width="1008" alt="screen shot 2017-03-24 at 9 36 57 am" src="https://cloud.githubusercontent.com/assets/3431090/24296424/73d1764e-1075-11e7-84e0-1a4b4318dbb7.png">

Any idea what could be causing this? 

--Thank you

**Comment by PanosFirmpas** [comment]
We are getting exactly the same and we have no idea where to go from there...

I took a screenshot with the console open, just in case it helps!

![screenshot from 2017-09-11 15-05-45](https://user-images.githubusercontent.com/3511306/30276171-3c6c2d78-9704-11e7-97c6-d2adf4580ab8.png)

**Comment by pkerpedjiev** [comment]
Did you run the docker container with the `SITE_URL` parameter set? There is a note in the documentation about that here:

https://github.com/hms-dbmi/higlass/wiki#running-locally

It looks like you're trying to access it from `bioinformatia.upo.es`. The Django application running the docker container will block requests from an unknown domain. If you've set that parameter, could you post the command that you used to run the container?

**Comment by PanosFirmpas** [comment]
Thanks that did the trick !    
    
One more thing, if you could help:
Can we use more than one IP in there? or maybe plug it somewhere else?    

We have a public and a local IP and we would ideally like it available in both without running two instances

**Comment by pkerpedjiev** [comment]
Unfortunately, right now that isn't possible. If you want, you can add a an issue to https://github.com/hms-dbmi/higlass-server/. 

In case you're interested, the piece of code that's responsible for setting the allowed hosts is here:

https://github.com/hms-dbmi/higlass-server/blob/a8ef72b6feff4404e93ae4b34590a73c7afb8ac3/higlass_server/settings.py#L79

I'm a little curious though, why would you have a public and private IP if they both point to the same instance? Can't you always just use the public IP to access it?

**Comment by PanosFirmpas** [comment]
Thanks again for the help !     
    
In the end, it looks like I spoke too soon,     
I thought our public IP is not locally available (I remember struggling with something in the past ), 
but I was wrong, the IP is available and Higlass works fine now ! :)

**Comment by pkerpedjiev** [comment]
Great! Glad to hear it.
