### ISSUE TITLE
Problem in Deployement

### ISSUE THREAD

**Issue by nadabrovitxka** [hms-dbmi/higlass-docker#139]
First of all, amazing work with HiGlass. It is truly a joy to work with it from your website.
I was trying to get it running locally to put in some of my own data. 
However the link you provide for deployment doesnt seem to be working.
https://raw.githubusercontent.com/hms-dbmi/higlass-docker/start_production.sh

**Comment by nadabrovitxka** [comment]
I just realized you have further information for deployment. Will this also run on a Mac or only on a machine running ubuntu?

**Comment by pkerpedjiev** [comment]
Thanks! 

The latest documentation for running locally is available here: https://github.com/hms-dbmi/higlass/wiki

Everything should work on Mac and Linux. If you encounter an error, can you post the output of the command you ran?

**Comment by nadabrovitxka** [comment]
Thanks.
I used the Dixon2012 .cool file you guys provide and it worked.
But had to use http://localhost:8989/admin/ instead of http://127.0.0.1:8989/admin to access the admin interface.

Maybe you could add a line saying that you should launch the website from the admin page. For some basic users like myself it might take a while to get it.

Will now try creating my own .cool files. will contact if I have problems.
Really cool software. Definitely beats some juicy competition.

**Comment by pkerpedjiev** [comment]
Thanks for the info! I changed the wiki to point to `localhost:8989` rather than `127.0.0.1:8989`. May I ask what you mean by "you should launch the website from the admin page"? 

After running the docker container, you should be able to go to http://localhost:8989 and see the higlass web page.

**Comment by nadabrovitxka** [comment]
I meant you should add that last sentence you wrote. I didn't realize immediately that it would be from that link that I should launch the higlass webpage. I assume it is quite obvious, but for wet lab people it might save a few tries.

**Comment by pkerpedjiev** [comment]
Ah yes. Good point! Added. Thank you.
