### ISSUE TITLE
higlass-docker app missing view header

### ISSUE THREAD

**Issue by danledinh** [hms-dbmi/higlass-docker#143]
I followed the "Running locally" instructions for running the docker container on an AWS EC2 instance (ubuntu 16.04). I'm using the latest docker image build. I ran a modified "docker run" command to access the website:

docker run --detach \
           --publish 80:80 \
           --volume ~/hg-data:/data \
           --volume ~/hg-tmp:/tmp \
           --name hg \
           gehlenborglab/higlass

I see my *.mcool file in the container and have ingested it. The website seems functional, except the view header bar is missing, so the app is not accessible. Is there something I'm missing?

![image](https://user-images.githubusercontent.com/12414317/34547227-877cec22-f0ae-11e7-83af-65ba7259820b.png)

**Comment by pkerpedjiev** [comment]
If it's on EC2, I suspect that you're hosting it somewhere that isn't localhost. Have you tried using the `-e SITE_URL=my.url.com` parameter to tell the docker container where you're hosting it on a foreign site?

Take a look at the wiki for more information: https://github.com/hms-dbmi/higlass/wiki

If that doesn't work, could you post a screenshot of the development console on your browser?

**Comment by danledinh** [comment]
That fixed it! Thanks!!! And, great work on viewer. It's a real asset to the community!!!

**Comment by pkerpedjiev** [comment]
Glad to hear that :)
