### ISSUE TITLE
personalize the browser page

### ISSUE THREAD

**Issue by hrhotz** [hms-dbmi/higlass-docker#146]
dear HiGlass Docker container developers

We are experimenting with the HiGlass Docker container in our institute. It is great! Thank you very much.

We currently have 5 servers on five different ports running. Each server has its own set of uploaded files. Our plan is to offer each lab its own HiGlass server, eventually.

Please allow me to ask for a new feature: It would be great to have the possibility to personalize the browser page for each lab. Something small like having an option to add a name in front of HiGlass in the top bar would already be enough.  Could something like this be implemented? Thank You.

Regards, Hans-Rudolf

**Comment by hrhotz** [comment]
Hi Peter

Thank you very much for your pointer. Although, your initial suggestion didn't work (i.e.: I got "Error response from daemon: Could not find the file higlass-website in container higlass-container"). I was successful (after putting the modified index.html file into the tmp  directory) with: 

`sudo docker exec higlass-container cp /tmp/test_index.html higlass-website/index.html`

This is exactly, what I have been looking for. Thank you!
Hans-Rudolf

**Comment by pkerpedjiev** [comment]
Excellent. Glad to hear you got it working!
