### ISSUE TITLE
Push to "higlass" repo on Docker Hub

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/higlass-docker#65]
We are currently pushing to "higlass-server", but since the Docker container is a lot more than that, we should push to "higlass" (I created the Docker Hub repo already): https://hub.docker.com/r/gehlenborglab/higlass/

@pkerpedjiev: do you agree?

**Comment by pkerpedjiev** [comment]
I don't disagree :)

**Comment by mccalluc** [comment]
Now pushing to `higlass`, and `higlass-server` is gone.
