### ISSUE TITLE
Figure out or work around big file upload timeouts

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass-docker#71]
Maybe there's a magical Nginx setting that does what we want... or maybe the django container should expose a port that can be hit just for uploads?

**Comment by mccalluc** [comment]
Here's what Nils saw:
```
curl -u username:password -F datafile=@Rao2014-GM12878-MboI-allreps-filtered.1kb.multires.cool -F filetype=cooler -F datatype=matrix -F coordSystem=hg19 http://localhost:8888/api/v1/tilesets/
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

**Comment by mccalluc** [comment]
@ngehlenborg or @pkerpedjiev : What size do we need to support? Right now I can reproduce failures with a 4G file. We can turn some limits off entirely, but that just means something else will be tripped downstream.

(The problem is not `client_max_body_size`, because we're under the cap set by hgserver_nginx.conf.)

**Comment by pkerpedjiev** [comment]
We should allow up to 30G for now so that we can upload the highest resolution files. In the future, maybe we can look into creating (or using) a script for uploading files larger than a certain size (e.g. 4G). 

As for timeouts, we can save some upload time by turning of hashed storage. Just comment out the `DEFAULT_FILE_STORAGE = 'tilesets.storage.HashedFilenameFileSystemStorage'` line in `higlass_server/settings.py` (this is done in the `develop` branch of higlass-server). This change should be backwards compatible with previous databases.

**Comment by mccalluc** [comment]
@pkerpedjiev 
> (this is done in the develop branch of higlass-server)

Can that be merged to master and given a tagged release? Or I suppose it could be tagged without merging, though that could get confusing over time. Not sure when you decide to merge dev to master...

(I don't think this is the limit I'm hitting right now now though, so not urgent.)

**Comment by pkerpedjiev** [comment]
OK, then I'll leave it out until I get back and can test it better or until timeouts become an issue.

**Comment by mccalluc** [comment]
Clarification:
- We are not going to be able to use chunked transfer encoding to upload entire files in a single POST for the sizes we are interested in.
- We may be able to use "chunked" transfer in a less formal sense, splitting the file into many small parts and POSTing each separately, and using a nginx plugin to handle it on the far side. but:
  - The nginx-upload project has not been touched since [2008](https://github.com/vkholodkov/nginx-upload-module) and it [may not work](https://coderwall.com/p/swgfvw/nginx-direct-file-upload-without-passing-them-through-backend) with recent nginx.
  - But https://github.com/pgaertig/nginx-big-upload or https://github.com/openresty/lua-resty-upload may work.

I'm going to close this and open a new one since the right direction is more clear now.
